[package]
name = "avian_core"
version = "0.1.0"
edition = "2021"

[dependencies]
hecs = { workspace = true }
nalgebra = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
hashbrown = { workspace = true }
smallvec = { workspace = true }
rustc-hash = { workspace = true }
rapier2d = { workspace = true }
avian_physics = { path = "../avian_physics" }