[package]
name = "avian_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
hecs = { workspace = true }
nalgebra = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
avian_core = { path = "../avian_core" }
avian_physics = { path = "../avian_physics" }
avian_telemetry = { path = "../avian_telemetry" }
tungstenite = { workspace = true }
rustc-hash = { workspace = true }
ctrlc = { workspace = true } # Dodano brakującą zależność

[[bin]]
name = "sim_server"
path = "src/bin/sim_server.rs"

[dev-dependencies]
bincode = { workspace = true }
